### ISSUE TITLE
missing parenting time questions to edit/review screen

### ISSUE THREAD

**Issue by RamiLorca** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#100]
Questions regarding the parenting time are not showing up in the review/edit screen.

**Comment by ekressmiller** [comment]
Just tried this again from the beginning and got the same issue when I chose "continue current parenting time order". I'm wondering if it's because the other two variables edited on the same screen are not yet defined so they block this from appearing on the review screen

```
  - Edit:
    - wants_parenting_time_change
    - requested_order
    - parenting_time_change_agreement

```
Since all three are on the same screen, I think maybe you could just delete the 2nd two from the edit list.

**Comment by ekressmiller** [comment]
also note minor typo on review screen:
<img width="331" alt="image" src="https://github.com/user-attachments/assets/8e774667-3ee2-435c-8382-7f147af703c2">
