### ISSUE TITLE
phone number collection --need to standardize validation/etc.

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#16]
Phone validation might be overly strict.  We discussed this before Rami and Hayden arrived, but I can't remember exactly where we landed. Let's discuss this at a meeting.  Compare with behavior in the child support motion tool where it validates less strictly and allows option not to include number.

**Comment by h-mcguire** [comment]
I'm not sure if it is actually required for filing but the motion for lists phone number as a part of the litigants info block. Here's a screenshot of what I mean: 
![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/106545452/9b16857c-fb90-43e0-8bce-7575f17a6883)

I removed validation since it didn't account for international numbers anyway, but left it a required field for now. Does the court not care about getting the phone number?
