### ISSUE TITLE
ID domestic violence explanation: 
User feedback: language
(`domestic_violence_exp`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#52]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `domestic violence explanation`
Details | Can you use the same language from LHI for the first sentence? "Briefly explain how "Other Parent Name" has been violent towards you."

Can you also move both sentences to be the label instead of subquestion?  (label_above_field will probably be a good option for these places where I'm suggesting a long label. -- https://docassemble.org/docs/fields.html#label%20above%20field )
Variable being sought | `domestic_violence_exp`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by h-mcguire** [comment]
Okay! In commit 404528f I updated the label above field in a variety of places. 
For this question specifically I changed the code to:

id: domestic violence explanation
question: |
  Explanation of domestic violence.
fields:
  Briefly explain how ${ other_parties[0].name } has been violent towards you. Tell the court if you have a personal protection order or a no contact order.: domestic_violence_exp
  label above field: True
  input type: area

I am hesitant about this iteration since it will display the word "domestic violence" pretty large on a screen of a person we are confident is experiencing dv. Let me know if you have any input about that.

**Comment by ekressmiller** [comment]
It's a good point, but I'm not sure it's worse than having " Briefly explain how ${ other_parties[0].name } has been violent towards you."  displayed large on the screen. (Let me know if you have thoughts about why it's worse.) Maybe we can leave it for now and see if Amy has thoughts.

**Comment by RamiLorca** [comment]
@ekressmiller There haven't been any changes to this screen since your last comment. Should I go ahead and put together an email for Amy?

**Comment by ekressmiller** [comment]
I would probably just send the interview to her (after we do our quick round of dev testing) and see if she raises it. Or if you want we can flag it when we send the interview to her for testing. I don't think it needs to get sent to her as a special separate issue.
