### ISSUE TITLE
ID DownloadScreen: 
User feedback: something
(`motion_re_change_of_domicile_download`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChangeOfDomicile#57]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `DownloadScreen`
Details | I'm not sure exactly what info on our site the help text is referencing when it talks about sample parenting schedules. (I know that's from LHI, so not on you!) We'll probably need to ask Amy what to do here.
Variable being sought | `motion_re_change_of_domicile_download`
Package version | `0.0.6`
Filename | `docassemble.MLHMotionRegardingChangeOfDomicile:data/questions/motion_regarding_change_of_domicile.yml`

**Comment by RamiLorca** [comment]
![Screenshot 2024-06-21 at 1 17 51 PM (2)](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110207826/bf556473-17af-4d59-9e83-1f123afe2628)

This is how this screen currently looks. Since I'm not seeing the help text you mentioned earlier, should I go ahead and close this out?

**Comment by ekressmiller** [comment]
Apologies I must have been on the wrong screen. I meant this screen:

id: wants parenting time change
Variable: wants_parenting_time_change

![image](https://github.com/mplp/docassemble-MLHMotionRegardingChangeOfDomicile/assets/110936328/5e0de90e-1d7a-4906-bba9-ef65996792e7)
